/* LUNA LANDEER -- sim.h
 *
 * THE RULES.  Pure C: no gb/gb.h in here, so tests/test_sim.c compiles this
 * with plain gcc -std=c99 and the physics can be run without an emulator.
 * main.c owns every variable; nothing in this file declares storage, only the
 * types and the functions that operate on them.
 *
 * Positions are WHOLE PIXELS plus a separate fraction byte, never 8.8 packed
 * into one word.  fix_step() needs the fraction as a byte it can point at, and
 * keeping the whole part a plain uint16_t leaves a value a tile lookup or a
 * camera can use directly.  HEIGHTS, by contrast, are 8 px TILE units -- see
 * terrain.h -- so a `<< 3` anywhere near terrain[] is the classic slip.
 */
#ifndef SIM_H
#define SIM_H

#include <stdint.h>

/* The thrust unit vectors, one per heading.  Pure C like everything else here:
 * tables.h is generated by tools/mktab.py and is included by main.c's own TU
 * through this file, so a `make` needs no Python and tests/test_sim.c gets it
 * from plain gcc like the rest of the physics. */
#include "tables.h"

/* ------------------------------------------------------------- 8.8 fixed */

/* Advance a sub-pixel accumulator by velocity v (8.8 fixed, px/frame) and
 * return the whole-pixel delta.
 *
 * *frac MUST point at one of the caller's own fraction bytes -- the fractional
 * remainder has to survive from one tick to the next, and that is the only
 * reason this takes a pointer.  Hand it a local (or a fresh uint8_t) and the
 * remainder is reset every tick: every fractional pixel is thrown away and the
 * motion quantises to whole pixels.  The ship still moves, so it looks like
 * "the physics is fine, it is just chunky" and nothing on screen says
 * otherwise -- which is exactly why the byte lives in the state struct. */
static int16_t fix_step(uint8_t *frac, int16_t v)
{
    int16_t acc = (int16_t)*frac + v;
    *frac = (uint8_t)(acc & 0xFF);
    return acc >> 8;
}

/* ---------------------------------------------------------------- gravity */

/* Gravity per tick as n/256 px/frame^2 -- n a POWER OF TWO and nothing else.
 * SDCC turns a power-of-two scale into a shift; any other constant silently
 * pulls in __mulint (~69 bytes) or __divsint (~231 bytes) for one line.
 *
 * 16/256 = 0.0625 px/frame^2 crosses the 144 px screen from rest in ~68 frames
 * (~1.1 s): long enough to react, short enough to read as falling.  This is a
 * CALIBRATION KNOB, not a derived value -- P5 owns the feel and is expected to
 * move it, so nothing below may assume this particular number. */
#define GRAV 16

/* ---------------------------------------------------------------- thrust */

/* Thrust per tick as n/256 px/frame^2 -- n a POWER OF TWO, same rule as GRAV
 * and for the same reason: SDCC turns a power-of-two scale into a shift and
 * anything else into __mulint.
 *
 * 32/256 is exactly 2 * GRAV, so with the nose up the net vertical
 * acceleration is (32 - 16)/256 px/frame^2 UPWARD and a full tank climbs.  A
 * "calibration knob" like GRAV -- P5 owns the feel, and nothing below assumes
 * this value, only that it beats GRAV.
 *
 * The ceiling is real: the table's unit vectors reach +-256, so THRUST * 256
 * has to fit int16_t and THRUST must stay <= 127 (127 * 256 = 32512).  The
 * tripwire below makes that a build error rather than a silent 16-bit wrap --
 * an overflow here thrusts the ship the wrong way and reads as a rotation bug. */
#define THRUST 32
typedef char thrust_fits_int16[(THRUST <= 127) ? 1 : -1];

/* Fuel units burned per tick of held thrust.  SUBTRACTED and never multiplied
 * or divided, so unlike GRAV and THRUST it is free of the power-of-two rule:
 * P5 tunes the burn rate and the tank size against each other with it. */
#define FUEL_BURN 1

/* A full tank, in fuel units -- one unit is one tick of held thrust at
 * FUEL_BURN 1, so this is 600 ticks, about ten seconds.  uint16_t in the
 * struct on purpose: a byte caps the tank at 255 ticks (four seconds), and
 * growing it later would be a refactor of this struct, every test and every
 * probe check -- the same cap-at-one-screen mistake terrain.h's
 * TERRAIN_MAX_TILES exists to avoid.  A CALIBRATION KNOB, P5's. */
#define FUEL_START 600

/* What this tick's buttons mean, decoded by main.c.  sim.h cannot see
 * J_UP/J_A/J_B -- it has no gb/gb.h -- and the decode is a wiring question
 * that belongs next to the joypad read anyway.
 *
 * THRUST is a LEVEL: it reads the held keys, so holding it keeps burning.
 * ROT_L/ROT_R are EDGES: one tick per press, or holding B would spin the ship
 * through a whole revolution. */
#define SHIP_THRUST 0x01
#define SHIP_ROT_L  0x02
#define SHIP_ROT_R  0x04

/* ------------------------------------------------------------------ ship */

typedef struct {
    uint16_t x;        /* left edge, whole screen px */
    uint16_t y;        /* top edge, whole screen px  */
    uint8_t  xf;       /* x fraction, 1/256 px       */
    uint8_t  yf;       /* y fraction, 1/256 px       */
    int16_t  vx;       /* 8.8 fixed px/frame         */
    int16_t  vy;
    uint8_t  heading;  /* index into thrust_dx/dy; 0 = nose up, += clockwise */
    uint16_t fuel;     /* fuel units left; 0 means thrust does NOTHING       */
} Ship;

/* One tick of the ship: rotate, burn, thrust, fall.  Still no collision and no
 * landing verdict -- those are P5's -- so the ship flies off the bottom of the
 * screen and keeps counting, which is what P3 did and what it still does.
 *
 * Fuel burns HERE and not in main.c's tick loop: the economy is part of the
 * step, so a frame that overruns its budget cannot quietly buy the player
 * more fuel or less.  The burn is a subtraction from the state, never
 * something the renderer does while drawing.
 *
 * The two fix_step() calls are still the whole of the sub-pixel behaviour:
 * both fraction bytes live in the struct, so the remainders carry across ticks
 * and the ship leaves rest a fraction of a pixel at a time. */
static void ship_step(Ship *s, uint8_t in)
{
    int16_t tx, ty;

    /* `& (ROT_STEPS - 1)` and not `% ROT_STEPS`: ROT_STEPS is a power of two
     * (tables.h says so), and a modulo through SDCC is __divsint, 231 bytes
     * for a wrap that costs one AND. */
    if (in & SHIP_ROT_L)
        s->heading = (uint8_t)((s->heading + ROT_STEPS - 1) & (ROT_STEPS - 1));
    if (in & SHIP_ROT_R)
        s->heading = (uint8_t)((s->heading + 1) & (ROT_STEPS - 1));

    s->vy += GRAV;

    /* An empty tank is not weak thrust, it is NO thrust: the guard is the
     * whole of "the ship is committed to its descent", and holding the button
     * against it changes the trajectory by nothing at all. */
    if ((in & SHIP_THRUST) && s->fuel) {
        s->fuel = (s->fuel > FUEL_BURN) ? (uint16_t)(s->fuel - FUEL_BURN) : 0;

        tx = thrust_dx[s->heading];
        ty = thrust_dy[s->heading];
        /* THRUST is a power of two, so the multiply is a shift.  The `>> 8` is
         * the table's 8.8 scale coming back out -- the table is +-256 and NOT
         * +-127, which tables.h says in full; shifting by 7 here would halve
         * the thrust and double nothing else. */
        s->vx += (int16_t)((THRUST * tx) >> 8);
        s->vy += (int16_t)((THRUST * ty) >> 8);
    }

    s->y = (uint16_t)(s->y + fix_step(&s->yf, s->vy));
    s->x = (uint16_t)(s->x + fix_step(&s->xf, s->vx));
}

#endif
