/* Generated by mktab.py - do not edit.  Run `python3 tools/mktab.py`. */
#ifndef TABLES_H
#define TABLES_H

#include <stdint.h>

/* Rotation steps in one full turn, 22.5 degrees each.  The ship's heading is
 * an index into the two arrays below, and this is a POWER OF TWO on purpose:
 * sim.h wraps the heading with `& (ROT_STEPS - 1)`, a mask, and SDCC only
 * turns a power-of-two modulo into one. */
#define ROT_STEPS 16

/* Thrust unit vectors, one per heading, in 8.8 FIXED POINT: a unit vector is
 * +-256 here, which is why these are int16_t and NOT int8_t.  +-256 does not
 * fit a byte -- an 8-bit table scaled to +-127 would need an extra `>> 7` on
 * every axis of every tick, and at +-256 the cardinals and the diagonals
 * alias into each other.  Consumers shift the product RIGHT BY 8.
 *
 * Index i points 22.5 * i degrees CLOCKWISE FROM UP (screen y grows
 * downward), so dy is NEGATIVE for up and index 0 is the spawn heading.  It
 * is the same heading mkgfx.py renders sprite frame i at: frame i and vector
 * i pointing different ways is the one bug this pairing can hide. */
static const int16_t thrust_dx[ROT_STEPS] = {
        0,    98,   181,   237,   256,   237,   181,    98,
        0,   -98,  -181,  -237,  -256,  -237,  -181,   -98,
};

static const int16_t thrust_dy[ROT_STEPS] = {
     -256,  -237,  -181,   -98,     0,    98,   181,   237,
      256,   237,   181,    98,     0,   -98,  -181,  -237,
};

#endif
