/* Generated by mklevel.py - do not edit.  Run `make level` to regenerate. */
#ifndef TERRAIN_H
#define TERRAIN_H

#include <stdint.h>

/* Both worlds are 160 px / 8 px per tile WIDE, and neither is one screen
 * wide plus a bit: 160 is NOT a power of two, so the wrap is two compares
 * (x < 0 -> x += 160; x >= 160 -> x -= 160) and never an `& WORLD_MASK`:
 * masking would wrap at 256 and put the seam off-screen. */
#define WORLD_COLS 20

/* The ceiling on a surface row, in 8 px TILE units -- the unit mkgfx.py
 * draws the terrain tiles in.  NOT pixels, and NOT the screen: mode 1 only
 * reaches row 15, the DESCENT profile reaches row 100, and the type has to
 * hold both without a refactor. */
#define TERRAIN_MAX_TILES 255

/* LANDER's surface row (tile units) at each world tile column.  Periodic
 * in WORLD_COLS: a ripple of period 4 inside a swell of period 20,
 * both dividing 20, so the wrap seam is invisible.  Rows 12..15.
 * One screen tall -- the world IS the screen, so main.c windows it
 * at row 0 and the offset arithmetic is the identity there. */
static const uint8_t terrain_lander[WORLD_COLS] = {
     12,  13,  13,  12,  15,  15,  15,  15,  14,  15,
     15,  14,  13,  12,  12,  13,  12,  13,  13,  12,
};

/* DESCENT's surface row (tile units) at each world tile column.  Periodic
 * in WORLD_COLS: a ripple of period 4 inside a swell of period 20,
 * both dividing 20, so the wrap seam is invisible.  Rows 96..100.
 * TALLER THAN A BG MAP (32 rows) and taller than the view (18):
 * there is no blit that puts these rows on one map, which is why
 * main.c draws a WINDOW of it rather than the whole profile. */
static const uint8_t terrain_descent[WORLD_COLS] = {
     96,  97,  97,  96, 100, 100, 100, 100,  98,  99,
     99,  98,  97,  97,  97,  97,  96,  97,  97,  96,
};

/* THE ACTIVE PROFILE, and the one symbol in this header that is not a
 * constant.  sim.h's ship_step() reads terrain[col] to find the ground
 * under the ship and tools/probe.py reads terrain out of the linker map, so
 * the two worlds share THIS name rather than one array being renamed per
 * mode -- a second name would break the collision call and the probe's
 * address lookup together, and the mismatch would look like a physics bug.
 * main.c assigns it; everything else just reads through it. */
static const uint8_t *terrain = terrain_lander;

/* The flat landing runs.  col0/col1 are inclusive world tile columns; mult
 * is the score multiplier for a landing that stays on the pad.  The span is
 * flat (mklevel.py asserts it for BOTH worlds), so terrain[col0..col1] is
 * all one row -- at a different depth in each: the DESCENT world's pads sit
 * on its own pad_rows, and sim.h's pad_mult() is a question about columns,
 * which is why the spans are shared. */
typedef struct {
    uint8_t col0;
    uint8_t col1;
    uint8_t mult;
} Pad;

#define PAD_COUNT 2
#define PAD_LOW      0
#define PAD_HIGH     1

static const Pad pads[PAD_COUNT] = {
    {  4,  7, 1 },  /* LOW */
    { 13, 14, 2 },  /* HIGH */
};

/* THE SKY.  main.c's row_blit() indexes this with
 * `world row & (STAR_ROWS - 1)`, so row N here is the sky at world rows
 * N, N + 16, N + 32 ... and the pattern REPEATS every 16 rows -- which is
 * what keeps the list 144 bytes instead of one row per row of world, and
 * lets it be a pure function of a WORLD row.  DESCENT streams its rows in
 * whatever order the camera asks for and re-blits them as the ring wraps,
 * so a table the ring had to carry would come back shuffled.
 *
 * THE LIST IS `column, tile` PAIRS, terminated by STAR_END (255), and not
 * a WORLD_COLS-wide row: row_blit() runs once per streamed row per tick
 * and probe.p13_descent's free-fall tick sits on the last frame it is
 * allowed, so the loop copies the 28 cells that ARE stars and not the 320
 * that are not.  Row N is padded out with STAR_END after its pairs and is
 * always read from the start, so the padding costs nothing.
 *
 * THE VALUES ARE TILE IDS, not indices: 3..6 are mkgfx.py's four stars
 * (two of them drawn dim, so the field has depth) and T_BLANK (0) is the
 * sky the loop already wrote.  28 of the 320 cells carry one.  mkgfx.py
 * asserts its own ids against those.
 *
 * NOT a hash of (row, col) -- a shift-and-XOR hash is linear over GF(2)
 * and the cells it picks land on a regular diagonal lattice.  It is an LCG
 * in tools/mklevel.py from a fixed seed instead, and `make level`
 * reproduces it byte for byte.  See that function for the argument. */
#define STAR_ROWS 16
#define STAR_TILES 4
#define STAR_END 255
#define STAR_STRIDE 9

static const uint8_t star_cells[STAR_ROWS][STAR_STRIDE] = {
    { 4, 4, 255, 255, 255, 255, 255, 255, 255 },
    { 5, 3, 255, 255, 255, 255, 255, 255, 255 },
    { 10, 4, 255, 255, 255, 255, 255, 255, 255 },
    { 10, 4, 255, 255, 255, 255, 255, 255, 255 },
    { 9, 6, 255, 255, 255, 255, 255, 255, 255 },
    { 255, 255, 255, 255, 255, 255, 255, 255, 255 },
    { 8, 5, 255, 255, 255, 255, 255, 255, 255 },
    { 10, 5, 255, 255, 255, 255, 255, 255, 255 },
    { 0, 5, 4, 3, 8, 6, 12, 6, 255 },
    { 2, 5, 18, 5, 19, 6, 255, 255, 255 },
    { 4, 3, 5, 4, 16, 5, 255, 255, 255 },
    { 18, 4, 19, 6, 255, 255, 255, 255, 255 },
    { 3, 5, 19, 6, 255, 255, 255, 255, 255 },
    { 4, 4, 5, 4, 255, 255, 255, 255, 255 },
    { 12, 4, 15, 5, 255, 255, 255, 255, 255 },
    { 3, 4, 8, 5, 17, 6, 255, 255, 255 },
};

#endif
