#!/usr/bin/env python3
"""Thrust directions for LUNA LANDEER -> tables.h

WHY A TABLE AND NOT A SINE.  The ship has exactly ROT_STEPS headings, so its
thrust vector is one of ROT_STEPS constants -- there is no angle to compute at
runtime.  sin()/cos() on an SM83 is a library routine costing more code than
the entire physics, which is why a rotating lander normally gets faked; here it
is bought once, at build time, by writing the sixteen vectors down.  mkgfx.py
makes the same trade for the sixteen sprite frames, and the two have to agree:
sprite frame i and vector i MUST point the same way, or the ship thrusts
sideways while it looks right.

REPRESENTATION -- the trap this phase calls out, so it is written here rather
than left in the reader's head.  These are int16_t at 8.8 fixed point, i.e.
+-256 for a unit vector.  A unit vector at 8.8 needs the full +-256, which does
NOT fit int8_t: scaling to +-127 and shifting by 7 is the alternative, and it
costs a second shift plus a rounding step on every axis of every tick.
Widening to int16_t costs 64 bytes of ROM once and nothing per tick, so the
table is int16_t.  The consequence that matters to the consumer: shift the
product right by 8, not by 7.

CONVENTION.  Index i is heading i, pointing 22.5 * i degrees CLOCKWISE FROM UP,
because screen y grows downward and the ship spawns nose-up:

    thrust_dy[i] = -cos(22.5 * i deg) * 256     (negative is up)
    thrust_dx[i] = +sin(22.5 * i deg) * 256     (positive is right)

ROT_STEPS is a POWER OF TWO on purpose: sim.h wraps the heading with
`& (ROT_STEPS - 1)`, which is a mask, and SDCC only turns a power-of-two
modulo into one -- anything else pulls in __divsint for a wrap.

tables.h is committed, so a plain `make` needs no Python.

    python3 tools/mktab.py
"""
import math

ROT_STEPS = 16              # 22.5 deg per step; see the mask note above

DIRS = []
for i in range(ROT_STEPS):
    a = 2.0 * math.pi * i / ROT_STEPS
    DIRS.append((int(round(math.sin(a) * 256)), int(round(-math.cos(a) * 256))))


def self_check():
    """Everything sim.h is entitled to assume about tables.h.

    Run BEFORE the file is written.  The two things that fail silently on
    hardware are a wrong quadrant (an overflowed entry points somewhere else
    entirely) and a table that is not square (mkgfx.py renders ROT_STEPS frames
    and the physics indexes ROT_STEPS vectors; a length mismatch is an
    out-of-bounds read, not a wrong picture).

    Both are recomputed from the FINISHED integer table, not from the floats it
    came from, so the assertion is about what is actually emitted."""
    assert len(DIRS) == ROT_STEPS, "expected %d directions, got %d" % (ROT_STEPS, len(DIRS))

    # The four cardinals, written out: a sign slip in the convention above shows
    # up nowhere else, and it is the difference between "nose up" and "nose down".
    assert DIRS[0] == (0, -256), DIRS[0]
    assert DIRS[ROT_STEPS // 4] == (256, 0), DIRS[ROT_STEPS // 4]
    assert DIRS[ROT_STEPS // 2] == (0, 256), DIRS[ROT_STEPS // 2]
    assert DIRS[3 * ROT_STEPS // 4] == (-256, 0), DIRS[3 * ROT_STEPS // 4]

    for i, (dx, dy) in enumerate(DIRS):
        assert -256 <= dx <= 256 and -256 <= dy <= 256, (i, dx, dy)
        # A unit vector, so the thrust MAGNITUDE is the same in every heading --
        # otherwise a diagonal would be free extra acceleration.
        assert abs(math.hypot(dx, dy) - 256.0) < 2.0, (i, dx, dy)
        a = 2.0 * math.pi * i / ROT_STEPS
        assert abs(dx / 256.0 - math.sin(a)) < 0.01, (i, dx)
        assert abs(dy / 256.0 + math.cos(a)) < 0.01, (i, dy)

    # THE WIDTH.  +-256 does not fit a byte, and an int8_t table would wrap the
    # cardinals to zero and the diagonals into the wrong quadrant.  This is the
    # assertion that says the type had to be widened; the generator's header
    # says which representation was chosen instead.
    assert any(abs(v) > 127 for d in DIRS for v in d), \
        "no entry exceeds int8_t: this table could have been bytes, and the " \
        "int16_t choice needs re-justifying"


self_check()

# ------------------------------------------------------------- generate ----
lines = [
    "/* Generated by mktab.py - do not edit.  Run `python3 tools/mktab.py`. */",
    "#ifndef TABLES_H",
    "#define TABLES_H",
    "",
    "#include <stdint.h>",
    "",
    "/* Rotation steps in one full turn, 22.5 degrees each.  The ship's heading is",
    " * an index into the two arrays below, and this is a POWER OF TWO on purpose:",
    " * sim.h wraps the heading with `& (ROT_STEPS - 1)`, a mask, and SDCC only",
    " * turns a power-of-two modulo into one. */",
    "#define ROT_STEPS %d" % ROT_STEPS,
    "",
    "/* Thrust unit vectors, one per heading, in 8.8 FIXED POINT: a unit vector is",
    " * +-256 here, which is why these are int16_t and NOT int8_t.  +-256 does not",
    " * fit a byte -- an 8-bit table scaled to +-127 would need an extra `>> 7` on",
    " * every axis of every tick, and at +-256 the cardinals and the diagonals",
    " * alias into each other.  Consumers shift the product RIGHT BY 8.",
    " *",
    " * Index i points 22.5 * i degrees CLOCKWISE FROM UP (screen y grows",
    " * downward), so dy is NEGATIVE for up and index 0 is the spawn heading.  It",
    " * is the same heading mkgfx.py renders sprite frame i at: frame i and vector",
    " * i pointing different ways is the one bug this pairing can hide. */",
    "static const int16_t thrust_dx[ROT_STEPS] = {",
]
for i in range(0, ROT_STEPS, 8):
    lines.append("    " + ", ".join("%5d" % DIRS[j][0] for j in range(i, i + 8)) + ",")
lines += ["};", "", "static const int16_t thrust_dy[ROT_STEPS] = {"]
for i in range(0, ROT_STEPS, 8):
    lines.append("    " + ", ".join("%5d" % DIRS[j][1] for j in range(i, i + 8)) + ",")
lines += ["};", "", "#endif", ""]

with open("tables.h", "w") as f:
    f.write("\n".join(lines))

print("tables.h: %d headings, dx %d..%d, dy %d..%d, int16_t (8.8, +-256)"
      % (ROT_STEPS,
         min(d[0] for d in DIRS), max(d[0] for d in DIRS),
         min(d[1] for d in DIRS), max(d[1] for d in DIRS)))
